/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyecto.analizadorlexico.visual;

import com.proyecto.analizadorlexico.model.Token;
import java.util.List;

/**
 *
 * @author david
 */
public class Informe extends javax.swing.JPanel {

    /**
     * Creates new form Informe
     */
    private InformeTokens tabla;
    private GenerarGraficos grafic;
    public Informe() {
        initComponents();
        tabla = new InformeTokens();
        this.add(tabla);
        tabla.setBounds(0, 50, 1050, 640);
        grafic = new GenerarGraficos();
        this.add(grafic);
        tabla.setVisible(true);
    }
    
    public void llenartabla(List<Token> lista){
        tabla.crearTabla(lista);
        tabla.setListaTokensinicial(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonClasificar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        buttonClasificar.setText("Clasificar");
        buttonClasificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClasificarMouseClicked(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Identificador", "Aritmetico", "Comparacion", "Logicos", "Asignacion", "Palabras Clave", "Constante", "Comentario", "Otros", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(buttonClasificar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClasificar))
                .addContainerGap(591, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClasificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClasificarMouseClicked
        String opcion= jComboBox1.getSelectedItem().toString();
        if (opcion.equals("Todos")) {
            tabla.crearTabla(tabla.getListaTokensinicial());
        }else{
            tabla.crearTabla(tabla.clasificado(opcion));
        }
    }//GEN-LAST:event_buttonClasificarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClasificar;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
