/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyecto.analizadorlexico.visual;


import com.proyecto.analizadorlexico.AnalizadorLexico;
import java.awt.Image;
import java.awt.Point;
import java.awt.MouseInfo;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTabbedPane;

/**
 *
 * @author david
 */
public class VentanaInicial extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicial
     */
    
    private int x ;
    private int y ;
    private String ubicacion;
    public VentanaInicial() {
        this.setUndecorated(true);
        initComponents();
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        this.setShape(forma);
        URL rutaca = AnalizadorLexico.class.getProtectionDomain().getCodeSource().getLocation(); 
        String ruta = rutaca.getPath();
        this.ubicacion = ruta.replace("target/classes/", "");
        imagenCierre(ubicacion);
        imagenMini(ubicacion);
        imagenMenu(ubicacion);
        labelTitulo.setText("Sin Titulo - Analizador Arch");
        JTabbedPane tab = new JTabbedPane();
        
        tab.setBounds(3, 70, 1080,650);
        this.add(tab);
        PanelPrincipal panel = new PanelPrincipal();
        tab.add(panel);
        tab.setTitleAt(0, "sin titulo");
    }
    
    public void imagenCierre(String direccion){
        ImageIcon image = new ImageIcon(direccion+"src/main/java/com/proyecto/analizadorlexico/Resource/cerrar1.png");
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        labelCierre.setIcon(icon);
        labelCierre.setText("");
        
    }
    public void imagenMini(String direccion){
        ImageIcon image = new ImageIcon(direccion+"src/main/java/com/proyecto/analizadorlexico/Resource/minimizarNegro.png");
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        labelMini.setIcon(icon);
        labelMini.setText("");
    }
    
    public void imagenMenu(String direccion){
        ImageIcon image = new ImageIcon(direccion+"src/main/java/com/proyecto/analizadorlexico/Resource/menu.png");
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        labelMenu.setIcon(icon);
        labelMenu.setText("");
        layeredPaneMenu.setBounds(5, 50, 100, 100);
        this.add(layeredPaneMenu);
        layeredPaneMenu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSuperior = new javax.swing.JPanel();
        labelCierre = new javax.swing.JLabel();
        labelMini = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelMenu = new javax.swing.JLabel();
        layeredPaneMenu = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelSuperior.setBackground(new java.awt.Color(204, 204, 204));
        PanelSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelSuperiorMouseDragged(evt);
            }
        });
        PanelSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelSuperiorMousePressed(evt);
            }
        });

        labelCierre.setText("label");
        labelCierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelCierreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelCierreMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelCierreMousePressed(evt);
            }
        });

        labelMini.setText("jLabel1");
        labelMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMiniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMiniMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelMiniMousePressed(evt);
            }
        });

        labelTitulo.setText("jLabel1");

        labelMenu.setText("jLabel1");
        labelMenu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                labelMenuFocusLost(evt);
            }
        });
        labelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelMenuMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(464, 464, 464)
                .addComponent(labelMini)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCierre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCierre)
                    .addComponent(labelMini)
                    .addComponent(labelTitulo)
                    .addComponent(labelMenu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layeredPaneMenu.setBackground(new java.awt.Color(204, 204, 204));
        layeredPaneMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        layeredPaneMenu.setOpaque(true);
        layeredPaneMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                layeredPaneMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                layeredPaneMenuMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 51, 255));
        jLabel1.setText("jLabel1");
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });

        layeredPaneMenu.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layeredPaneMenuLayout = new javax.swing.GroupLayout(layeredPaneMenu);
        layeredPaneMenu.setLayout(layeredPaneMenuLayout);
        layeredPaneMenuLayout.setHorizontalGroup(
            layeredPaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPaneMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layeredPaneMenuLayout.setVerticalGroup(
            layeredPaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPaneMenuLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(layeredPaneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layeredPaneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 579, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSuperiorMousePressed
        // TODO add your handling code here:
        int x =evt.getX();
        int y =evt.getY();
        layeredPaneMenu.setVisible(false);

    }//GEN-LAST:event_PanelSuperiorMousePressed

    private void PanelSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSuperiorMouseDragged
        // TODO add your handling code here:
        Point point = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(point.x-x, point.y-y);
    }//GEN-LAST:event_PanelSuperiorMouseDragged

    private void labelCierreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCierreMousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_labelCierreMousePressed

    private void labelCierreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCierreMouseEntered
        // TODO add your handling code here:
        ImageIcon image = new ImageIcon(ubicacion+"src/main/java/com/proyecto/analizadorlexico/Resource/cerrar-sesion.png");
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        labelCierre.setIcon(icon);
    }//GEN-LAST:event_labelCierreMouseEntered

    private void labelCierreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCierreMouseExited
        
        ImageIcon image = new ImageIcon(ubicacion+"src/main/java/com/proyecto/analizadorlexico/Resource/cerrar1.png");
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        labelCierre.setIcon(icon);
    }//GEN-LAST:event_labelCierreMouseExited

    private void labelMiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMiniMouseEntered
        ImageIcon image = new ImageIcon(ubicacion+"src/main/java/com/proyecto/analizadorlexico/Resource/minimizarGris.png");
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        labelMini.setIcon(icon);
    }//GEN-LAST:event_labelMiniMouseEntered

    private void labelMiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMiniMouseExited
        ImageIcon image = new ImageIcon(ubicacion+"src/main/java/com/proyecto/analizadorlexico/Resource/minimizarNegro.png");
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        labelMini.setIcon(icon);
    }//GEN-LAST:event_labelMiniMouseExited

    private void labelMiniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMiniMousePressed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_labelMiniMousePressed

    private void labelMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenuMousePressed
        // TODO add your handling code here:
        if(layeredPaneMenu.isVisible()){
            layeredPaneMenu.setVisible(false);
        }else{
            layeredPaneMenu.setVisible(true);
        }
    }//GEN-LAST:event_labelMenuMousePressed

    private void labelMenuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_labelMenuFocusLost
        // TODO add your handling code here:
        layeredPaneMenu.setVisible(false);
    }//GEN-LAST:event_labelMenuFocusLost

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel1FocusGained

    private void labelMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenuMouseExited
        // TODO add your handling code here:
        //layeredPaneMenu.setVisible(false);
    }//GEN-LAST:event_labelMenuMouseExited

    private void layeredPaneMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_layeredPaneMenuMouseEntered
        // TODO add your handling code here:
        layeredPaneMenu.setVisible(true);
    }//GEN-LAST:event_layeredPaneMenuMouseEntered

    private void layeredPaneMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_layeredPaneMenuMouseExited
        // TODO add your handling code here:
        layeredPaneMenu.setVisible(false);
    }//GEN-LAST:event_layeredPaneMenuMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCierre;
    private javax.swing.JLabel labelMenu;
    private javax.swing.JLabel labelMini;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLayeredPane layeredPaneMenu;
    // End of variables declaration//GEN-END:variables
}
